config/routes.rb
Rails.application.routes.draw do
  # GET /about ; looks for about_controller in controllers
  # specify as so all paths referring to this knows!
  get "about_me", to: "about#index", as: :about

  # sign up page
  get "sign_up", to: "registrations#new"
  # to create user
  post "sign_up", to:"registrations#create"
  # log into user via sessions; get for form, post for form submission
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  # logout user by destroying session
  delete "logout", to:"sessions#destroy"

  # updating password
  get "password", to: "passwords#edit"
  # patch so we can update it for the user
  patch "password", to: "passwords#update"

  # resetting password
  get "password/reset", to: "password_resets#new"
  # sends out email
  post "password/reset", to: "password_resets#create"
  # to actually perform the reset
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  # for twitter auth
  get "/auth/twitter/callback", to: "omniauth_callbacks#twitter"

  # need to define route route! same as get "/" or ""
  root to: "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
# helps assign pertaining to the current request;
# so diff ppl logged in on have their own Current.user
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/user.rb
# email:string
# password_digest:string
#
# password:string virtual
# password_confirmation:string virtual

class User < ApplicationRecord
    # from rails; virtual password, not saved to db
    # runs thru bcrypt encryption to save as a hash
    # (have to uncomment in gem file)
    # we only deal with password & password confirmation,
    # and bcrypt converts it to the password_digest to
    # save in db
    has_secure_password

    # validations to make sure all fields are there
    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "Must be a valid email address!" }
end

app/controllers/about_controller.rb
# needs to match file name in CamelCase
# inherits from ApplicationController to get all funtionality
class AboutController < ApplicationController
    def index
        # uses rails default render in views > about > index.html.erb
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # before ANY actions anywhere else! any other methods
    # request things anywhere else
    before_action :set_current_user

    def set_current_user
         # load user if user is logged in
         if session[:user_id]
            # find_by will not throw error if cannot find user
            Current.user = User.find_by(id: session[:user_id])
        end
    end

    def require_user_logged_in!
        redirect_to sign_in_path, alert: "You must be signed in first!" if Current.user.nil?
    end
end

app/controllers/main_controller.rb
# needs to match file name in CamelCase
# inherits from ApplicationController to get all funtionality
class MainController < ApplicationController
    # uses rails default render in views > main > index.html.erb
    def index
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
    def twitter
        render plain: "Success!"
    end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by(email: params[:email])

        if @user.present?
            # send email to certain person (with)
            # deliver_later sends email out in a background job (efficiency)
            PasswordMailer.with(user: @user).reset.deliver_now
        end

        redirect_to root_path, notice: "If an account with that email was found,
                an email link was sent to reset your password!"
    end

    def edit
        # look for user with signed id
        @user = User.find_signed!(params[:token], purpose: "password_reset")
        rescue ActiveSupport::MessageVerifier::InvalidSignature
            redirect_to sign_in_path, alert: "You did not reset your password in time. ): Please try again!"
    end

    def update
        # look for user with signed id
        @user = User.find_signed!(params[:token], purpose: "password_reset")
        if @user.update(password_params)
            redirect_to sign_in_path, notice: "Your password was successfully reset! Please sign in."
        else
            render :edit
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    # defined in parent so we can reuse it
    # will not render rest of code
    before_action :require_user_logged_in!

    def edit
    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Password updated!"
        else
            render :edit
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registrations_controller.rb
# needs to match file name in CamelCase
# inherits from ApplicationController to get all funtionality
class RegistrationsController < ApplicationController
    def new
        # use instance variables so it can be visible in the views
        @user = User.new
    end

    def create
        # data returned from form submitted in new is in params! user data in user
        # use private function to assign only certain items
        @user = User.new(user_params)
        # if we save to db successfully, redirect to root_path; else re-render page
        if @user.save  
            # to log in a user more securely, session is an encrypted hash in ruby
            session[:user_id] = @user.id
            redirect_to root_path, notice: "Successfully created account!"
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
# needs to match file name in CamelCase
# inherits from ApplicationController to get all funtionality
class SessionsController < ApplicationController
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "You have been logged out!"
    end

    def new
    end

    def create
        # find user in db by email
        user = User.find_by(email: params[:email])
        # check if email exists & password matches (authenticate comes w rails)
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Successfully logged in!"
        else
            flash[:alert] = "We did not recognize your email or password!"
            render :new
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<%# all other code is in wrapper layout file,
application.html.erb %>
<div class="d-flex align-items-center justify-content-center">
    <h1>About!</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby Tweet Web App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# add custom css, js, etc here %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@800&family=Poppins:wght@300&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag   'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= render partial: "shared/flash"%>
      <%= yield %>
    </div>
  </body>
</html>

<%# js, stylesheets, favicons, etc defined here! wraps
views by replacing yield w our content in views %>

app/views/main/index.html.erb
<div class="d-flex flex-column align-items-center justify-content-center">
    <h1>Welcome to Scheduled Tweets!</h1>
</div>

app/views/password_resets/edit.html.erb
<div class="d-flex flex-column align-items-center justify-content-center">
    <h1>Reset Your Password!</h1>

    <%# can use table from db to make a form! %>
    <%# looks for a url helpe post request %>
    <%# NEED TO HAVE local: true to redirect locally!!! %>
    <%= form_with model: @user, url: password_reset_edit_path(token: params[:token]), local: true do |form| %>
        <% if form.object.errors.any? %>
            <div class="alert alert-warning mt-4">
                <% form.object.errors.full_messages.each do |message| %>
                    <div><%= message %></div>
                <% end %>
            </div>
        <% end %>
        <div class="mb-3">
            <%= form.label :password %>
            <%= form.password_field :password, class:"form-control", placeholder: "your password" %>
        </div>
        <div class="mb-3">
            <%= form.label :password_confirmation %>
            <%= form.password_field :password_confirmation, class:"form-control", placeholder: "confirm password" %>
        </div>
        <div class="mb-3">
            <%= form.submit "Reset Password!", class:"btn" %>
        </div>
    <% end %>
</div>

app/views/password_resets/new.html.erb
<div class="d-flex flex-column align-items-center justify-content-center">
    <h1>Forgot Your Password?</h1>

    <%# can use table from db to make a form! %>
    <%# looks for a url helpe post request %>
    <%# NEED TO HAVE local: true to redirect locally!!! %>
    <%= form_with url: password_reset_path, local: true do |form| %>

        <div class="mb-3"> 
            <%= form.label :email %>
            <%= form.text_field :email, class:"form-control", placeholder: "rashi.ghosh@cerner.com" %>
        </div>
        <div class="mb-3">
            <%= form.submit "Send Email!", class:"btn" %>
        </div>
    <% end %>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success mt-4">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Ruby Scheduled Tweets", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Home", root_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%# name, route path, class name %>
        <%= link_to "About", about_path, class:"nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav ms-auto mb-2 mg-lg-0">
      <% if Current.user %>
        <li class="nav-item">
            <%= link_to "Edit Password", password_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Log Out", logout_path, method: 'delete', class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign In", sign_in_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", sign_up_path, class:"nav-link" %>
        </li>
      <% end %>
    </ul>
    
  </div>
</nav>